version: "3.7"

services:
  frontend:
    container_name: zappts-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
