# build
FROM node:14.15.4-alpine as build
WORKDIR /app
COPY . /
RUN npm ci
RUN npm run build

# production
FROM nginx:1.19.6-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
